server:
  port: 8081

spring:
#  cloud:
#    discovery:
#      enabled: true
#  application:
#    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/mischief?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: barbecue
    driverClassName: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: jdbc:postgresql://localhost:5432/mischief?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    user: postgres
    password: barbecue

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  token_secret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  token_expired: 3600000
